
esphome:
  name: esp32-s3-eth-01
  friendly_name: esp32-s3-eth-01

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "E1nBHsGaaRced5xM4zhkXgH3Hkxj244iKIPHs6HFXXE="

ota:
  - platform: esphome
    password: "e49a5bc7b60b264ce308cf505fbe2bb4"

ethernet:
  type: W5500
  clk_pin: GPIO13
  mosi_pin: GPIO11
  miso_pin: GPIO12
  cs_pin: GPIO14
  interrupt_pin: GPIO10
  reset_pin: GPIO9

