[package]
name = "farmbot"
version = "0.1.0"
authors = ["georgewhewell <georgerw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
log = "0.4.0"
env_logger = "0.7.1"
btleplug = { git = "https://github.com/icewind1991/btleplug.git", branch = "pass-le-discover-info" }
serde = { version = "1.0", features = ["derive"] }
serde-hex = "0.1.0"
toml = "0.4.2"
rumqttc = "0.0.7"
serde_json = "1.0"
titlecase = "1.1"
linux-embedded-hal = "0.3"
embedded-hal = "1.0.0-alpha.1"
pwm-pca9685 = "0.2.0"
bme280 = "0.2.1"
vl53l0x = "0.3.1"
i2cdev = "0.4.4"
eeprom24x = "0.3.0"
rand = "0.7.3"