theme = "native"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/nix/store"
alias = "/nix/store"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "sound"
device_kind = "source"

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %R"
