name: build
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - "*"

jobs:
  build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v12
        with:
          name: rock5b-nixos
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build -L
