[package]
name = "weather"
version = "0.1.0"
authors = ["georgewhewell <georgerw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
bme280 = "0.2.1"
linux-embedded-hal = "0.3"
vl53l0x = "0.3.1"
mqtt-async-client = { git = "https://github.com/fluffysquirrels/mqtt-async-client-rs.git" }
shared-bus = { version = "0.1.4", features = [ "std" ] }
crossbeam-channel = "0.4"
tokio = "0.2.22"
async-channel = "1.4.0"
futures = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.hal]
package = "embedded-hal"
version = "0.2"