[package]
name = "weather"
version = "0.1.0"
authors = ["georgewhewell <georgerw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
linux-embedded-hal = "0.3"
bme280 = "0.2.1"
vl53l0x = "0.3.1"
pwm-pca9685 = "0.2.0"
mqtt-async-client = { git = "https://github.com/fluffysquirrels/mqtt-async-client-rs.git" }
shared-bus = { version = "0.1.4", features = [ "std" ] }
tokio = { version = "0.2", features = ["macros"] }
async-channel = "1.4.0"
futures = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
btleplug = { git = "https://github.com/icewind1991/btleplug.git", branch = "pass-le-discover-info" }
anyhow = "1.0"
toml = "0.4.2"
warp = "0.2"
i2cdev = "0.4.4"
embedded-hal = "1.0.0-alpha.1"

[dependencies.hal]
package = "embedded-hal"
version = "0.2"
