apiVersion: v1
kind: Service
metadata:
  name: placeholder
  labels:
    app: placeholder
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: placeholder
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: placeholder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
      - name: placeholder
        image: georgewhewell/placeholder 
        ports:
        - containerPort: 80
