apiVersion: v1
kind: Secret
metadata:
  name: db-passwords
data:
  djangouserpw: postgrespassword
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk:
    pdName: postgres-disk
    fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
         name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-pass
              key: pg-pass
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgres-data
