{
 "title": "GPS / GNSS",
 "tags": [
  "gnss",
  "gps"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(gpsd_version_info, instance)"
    }
   },
   {
    "name": "gnssid",
    "label": "0=GPS, 2=Galileo, 3=Beidou, 5=QZSS, 6-GLONASS",
    "query": {
     "query": "label_values(gpsd_sat_ss, gnssid)"
    }
   },
   {
    "name": "rateinterval",
    "label": "rateinterval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "percentiles",
    "label": "percentiles",
    "query": "0.05, 0.10,0.20,0.33,0.50,0.63,0.80,0.90,0.95"
   },
   { "name": "used", "label": "Sat used", "query": { "query": "label_values(gpsd_sat_ss,used)" } },
   {
    "name": "device",
    "label": "PPS device",
    "query": {
     "query": "label_values(gpsd_pps_histogram_bucket,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpsd_lat{instance=~\"$instance\"}",
     "legendFormat": "Latitude"
    },
    {
     "expr": "gpsd_long{instance=~\"$instance\"}",
     "legendFormat": "Longitude"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpsd_sat_seen{instance=~\"$instance\"}",
     "legendFormat": "Satellites Seen: "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpsd_sat_used{instance=~\"$instance\"}",
     "legendFormat": "Satellites Used:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpsd_mode{instance=~\"$instance\"}",
     "legendFormat": "GPS Mode:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpsd_status{instance=~\"$instance\"}",
     "legendFormat": "GPS Status:"
    }
   ]
  },
  {
   "title": "Sats used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gpsd_sat_used{instance=~\".*$instance.*\"}",
     "legendFormat": "Satellites Used"
    },
    {
     "expr": "gpsd_sat_seen{instance=~\".*$instance.*\"}",
     "legendFormat": "Satellites Seen"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (gnssid) (gpsd_used{instance=~\"$instance\"})",
     "legendFormat": "{{gnssid}}"
    }
   ]
  },
  {
   "title": "GPS Details",
   "type": "table",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "gpsd_version_info{instance=~\"$instance\",  device!~\"/dev/pps.*\"}"
    },
    {
     "expr": "gpsd_devices_info{instance=~\"$instance\",device!~\"/dev/pps.*\"}"
    },
    {
     "expr": "histogram_quantile($percentiles, sum(rate(gpsd_pps_histogram_bucket{instance=~\"$instance\"}[$rateinterval])) by (le))",
     "legendFormat": "Percentile"
    }
   ]
  },
  {
   "title": "Satellite Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (gnssid) (gpsd_used{instance=~\"$instance\"} == 1)",
     "legendFormat": "used gnssid {{gnssid}}"
    }
   ]
  },
  {
   "title": "Dilution of precision",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gpsd_gdop{instance=~\"$instance\"}",
     "legendFormat": "Geometric (hyperspherical) DOP"
    },
    {
     "expr": "gpsd_hdop{instance=~\"$instance\"}",
     "legendFormat": "Horizontal DOP"
    },
    {
     "expr": "gpsd_pdop{instance=~\"$instance\"}",
     "legendFormat": "Position (spherical/3D) DOP"
    },
    {
     "expr": "gpsd_tdop{instance=~\"$instance\"}",
     "legendFormat": "Time DOP {{instance}}"
    },
    {
     "expr": "gpsd_vdop{instance=~\"$instance\"}",
     "legendFormat": "Vertical (altitude) DOP"
    },
    {
     "expr": "gpsd_ydop{instance=~\"$instance\"}",
     "legendFormat": "Longitudinal DOP"
    },
    {
     "expr": "gpsd_xdop{instance=~\"$instance\"}",
     "legendFormat": "Latitudinal DOP"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "gpsd_altMSL{instance=~\"$instance\"}",
     "legendFormat": "Altitude"
    }
   ]
  },
  {
   "title": "Coordinates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "gpsd_lat{instance=~\"$instance\"}  >=10",
     "legendFormat": "Latitude"
    },
    {
     "expr": "gpsd_long{instance=~\"$instance\"}  >=4",
     "legendFormat": "Longitude"
    }
   ]
  },
  {
   "title": "Histograms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clock offset from PPS (Histogram)",
   "type": "heatmap",
   "description": "$__interval",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(gpsd_pps_histogram_bucket{instance=~\".*$instance.*\",device=\"$device\"}[$rateinterval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": " (+-) $percentiles Percentile Clock Offset from PPS (from Histogram data)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentiles, sum(rate(gpsd_pps_histogram_bucket{instance=~\".*$instance.*\",device=\"$device\"}[$rateinterval])) by (le))",
     "legendFormat": "${percentiles}th percentile positive Clock offset"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(gpsd_pps_histogram_bucket{instance=~\".*$instance.*\",device=\"$device\"}[$rateinterval])) by (le))",
     "legendFormat": "50th percentile negative Clock offset"
    },
    {
     "expr": "histogram_quantile((1- $percentiles), sum(rate(gpsd_pps_histogram_bucket{instance=~\".*$instance.*\",device=\"$device\"}[$rateinterval])) by (le))",
     "legendFormat": "(100-${percentiles})th percentile negative Clock offset"
    }
   ]
  },
  {
   "title": "x-offset in meters to stationary geo point ($rateinterval)",
   "type": "heatmap",
   "description": "$__interval",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(gpsd_geo_bearing_x_histogram_bucket{instance=~\".*$instance.*\"}[$rateinterval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "y-offset in meters to stationary geo point ($rateinterval)",
   "type": "heatmap",
   "description": "$__interval",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(gpsd_geo_bearing_y_histogram_bucket{instance=~\".*$instance.*\"}[$rateinterval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "offset in meters stationary geo point ($rateinterval)",
   "type": "heatmap",
   "description": "$__interval",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(gpsd_geo_offset_m_histogram_bucket{instance=~\".*$instance.*\"}[$rateinterval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Per Satellite detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Satellite Azimuth, degrees from true north",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "gpsd_sat_az{gnssid=~\"$gnssid\",instance=~\"$instance\", used=~\".*$used.*\"} >= -1",
     "legendFormat": "Sat {{PRN}}"
    }
   ]
  },
  {
   "title": "Satellite Elevation in degrees",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "gpsd_sat_el{gnssid=~\"$gnssid\",instance=~\"$instance\",used=~\".*$used.*\"} >= -1",
     "legendFormat": "Sat {{PRN}}"
    }
   ]
  },
  {
   "title": "Satellite Signal to Noise ratio",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dBHz" } },
   "targets": [
    {
     "expr": "gpsd_sat_ss{gnssid=~\"$gnssid\",instance=~\"$instance\",used=~\".*$used.*\"}",
     "legendFormat": "Sat {{PRN}}"
    }
   ]
  },
  {
   "title": "GPS Quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Error margin",
     "type": "graph",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gpsd_sep{instance=~\"$instance\"}",
       "legendFormat": "Estimated Spherical (3D) Position Error"
      },
      {
       "expr": "gpsd_eph{instance=~\"$instance\"}",
       "legendFormat": "Estimated horizontal Position (2D) Error in meters"
      },
      {
       "expr": "gpsd_epc{instance=~\"$instance\"}",
       "legendFormat": "Estimated climb error in meters per second"
      },
      {
       "expr": "gpsd_eps{instance=~\"$instance\"}",
       "legendFormat": "Estimated speed error in meters per second"
      },
      {
       "expr": "gpsd_epv{instance=~\"$instance\"}",
       "legendFormat": "Estimated vertical error in meters"
      },
      {
       "expr": "gpsd_epy{instance=~\"$instance\"}",
       "legendFormat": "Latitude error estimate in meters"
      },
      {
       "expr": "gpsd_epx{instance=~\"$instance\"}",
       "legendFormat": "Longitude error estimate in meters"
      }
     ]
    },
    {
     "title": "ECEF Y velocity",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 83 },
     "yaxes": [
      { "format": "lengthm" }
     ],
     "targets": [
      {
       "expr": "gpsd_ecefy{instance=~\"$instance\"}",
       "legendFormat": "ECEF Y position in meters"
      }
     ]
    },
    {
     "title": "ECEF X velocity",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "lengthm" }
     ],
     "targets": [
      {
       "expr": "gpsd_ecefx{instance=~\"$instance\"}",
       "legendFormat": "ECEF X position in meters"
      }
     ]
    },
    {
     "title": "ECEF Z velocity",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 83 },
     "yaxes": [
      { "format": "lengthm" }
     ],
     "targets": [
      {
       "expr": "gpsd_ecefz{instance=~\"$instance\"}",
       "legendFormat": "ECEF Z position in meters"
      }
     ]
    }
   ]
  }
 ]
}