[package]
name = "natures_prophet"
version = "0.1.0"
authors = ["georgewhewell <georgerw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.4.1"
rand = "0.7.3"
sysfs-pwm = "^0.1.0"
