# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gonbdserver-unstable-${version}";
  version = "2017-04-25";
  rev = "9abaa2fed84fea02e090dbdd16be7bd20162e8b6";

  goPackagePath = "github.com/abligh/gonbdserver";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/abligh/gonbdserver";
    sha256 = "00k799zszdlbqzkzl74qq7nh1akhl0z6yg89fv48xf4447nmz1lb";
  };

  goDeps = ./deps.nix;
  buildFlags = "--tags noceph";

  meta = {};
}
