# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/kardianos/osext";
    fetch = {
      type = "git";
      url = "https://github.com/kardianos/osext";
      rev = "ae77be60afb1dcacde03767a8c37337fad28ac14";
      sha256 = "056dkgxrqjj5r18bnc3knlpgdz5p3yvp12y4y978hnsfhwaqvbjz";
    };
  }
  {
    goPackagePath = "github.com/sevlyar/go-daemon";
    fetch = {
      type = "git";
      url = "https://github.com/sevlyar/go-daemon";
      rev = "e49ef56654f54139c4dc0285f973f74e9649e729";
      sha256 = "1nfrvvkr57gk9p7d2q6g793kng4bp1c72aprvlaz95xx2sihnc79";
    };
  }
  {
    goPackagePath = "github.com/traetox/goaio";
    fetch = {
      type = "git";
      url = "https://github.com/traetox/goaio";
      rev = "46641abceb1767a924e6b6a1ce3dd3204ca29374";
      sha256 = "0dvw6li2rab06312ka3mz3v6m6iz0v7g2gn7ni6v0a2y1yqayyc5";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "5ccada7d0a7ba9aeb5d3aca8d3501b4c2a509fec";
      sha256 = "0bdwdxy2gz48icnh023r5fga3z4x6c8gry8jlfjqr5w12y3s281g";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "d670f9405373e636a5a2765eea47fac0c9bc91a4";
      sha256 = "1w1xid51n8v1mydn2m3vgggw8qgpd5a5sr62snsc77d99fpjsrs0";
    };
  }
]
