{...}: {
  esphome.settings.esp32.framework.sdkconfig_options = {
    CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM = "16";
    CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM = "32";
    CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM = "32";
    CONFIG_ESP32_WIFI_TX_BUFFER_TYPE = "1";
    CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED = "y";
    CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED = "y";
    CONFIG_ESP32_WIFI_NVS_ENABLED = "n";

    CONFIG_LWIP_MAX_SOCKETS = "16";
    CONFIG_LWIP_TCP_MSS = "1436";
    CONFIG_LWIP_TCP_WND = "65535";
    CONFIG_LWIP_TCPIP_RECVMBOX_SIZE = "32";
    CONFIG_LWIP_TCPIP_TASK_STACK_SIZE = "4096";
  };
}
