wifi_ssid: ENC[AES256_GCM,data:PKNdbv1PHIq+eMn8URPil6w=,iv:xZJd+AQXiq1XghWZ+Wew2qr+XXr5aosFrB1PlfjBuDQ=,tag:HR+YKqq0O7/C4meJRXyDew==,type:str]
web_password: ENC[AES256_GCM,data:4CkeUWY=,iv:u0NE2Zgru3PznuCEbnEWj6AHK5dK1YCas+6mNdIY7g0=,tag:vL6n04LTIz3aClcWt7uvDQ==,type:str]
ota_key: ENC[AES256_GCM,data:6KlYFq3nIEkz7Imm64o5mHEr9anpf7YiYToJNpenHTQ=,iv:CQ9WeReDlHMWFWDJyKLzaS+jP4iMoCutB5Dk93Jo0xQ=,tag:S0WhhuPfh62mDUnEEtSU5Q==,type:str]
api_key: ENC[AES256_GCM,data:96Cg/hhr/miIwlPNy/4IAMfWVqZcjEhXb+Klru/IEK4R9suQrhI5uvJWPs0=,iv:R7+a+5FQMyLH0+tAp5q7SUFoa3o2ydiQXKDYK0gwMac=,tag:O3X9gbLwnd8mcL5knzJtiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a0pFd0lFTXBTS25QQkxC
            RTgxYkFSd0ZUbGpiay9wVUxHOFpSTldYWEM4CnNQblhQL3RPL0FpbGhpVlZ3N2Jp
            OVFIa0Vmck9qVXA0K1kyTk5tZ0NvTjAKLS0tIFQvN0NzK3YxSHZXdjJXTVo1Kysx
            b0lCeUdpUzFHWEpkdnBOOGVOcTlIbDAK3hS3kpKFfDxv76J6fIMBmrZj8SVeFuoD
            6fQBDFdggaCjM1odfjU0zLqNSfk9Q70JgUK3a9lHqQuSSecXIxCqVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1evpz8q2vsh029ph5v63muxk7ml7vg99ygqd7vg09e2azuff2a3pq34lal4
    lastmodified: "2026-06-15T01:07:04Z"
    mac: ENC[AES256_GCM,data:UiDbBBQ/Lx9yNRoPdkV9HHY4muB9/OYPpBvAqiRjiV+rkxLKp2U8UKsEWQyU7EvEBJt2DBvs+v8PE5gKaHDBgCjw1QQbx51RIdCdcIn5/RKZPoBETiduNG5v9+2ji8QCag/RU/P9uBjJ+xxFRfHLqbDOkEbkdt7BgwRznfM4RYU=,iv:e33hMd5kwyvpAQE2979VgUZlip011hJDUVaaxsxSNYI=,tag:KGU5x/Q9SKFfkPbYE4XVGg==,type:str]
    pgp:
        - created_at: "2026-09-05T10:09:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+IYLURd8XmyARAAtABvGYYeI9Zx/grANjgiOx1GhH+UyLmhEIfRQ5HcNKEM
            vG2YPPDzwuob84E8NWGLmJB6QERZBvKwMONuNa4UjAKoCPQx2HMd/W7/x9i/QvWe
            y3v7pgV5reBSyP6b27NEh7RvHuB7QY8tmiDSKeHf3+JxzqcnkF6nAjkzSC781EP2
            ci7tdwzaVmxMBjmQLpikAndbveMbzUjydeG2x9UFlcfTbn4oPss1/4ibwIOfRB+E
            yDaJLAQndtgbUvur+92YO//DTGhRYLl9j36nR/ecMHmVIqL/cWRWTe33SeQ9d2wT
            2Zn53lTChPSLVnqxWkgjpF/vjdOmBf8Mo5POfF46g82p9E7KhvBOzkv4Q9H8HTTg
            351pJ5jV7vpqZDAPLd+pDZZEyC6Vnra4QF/zGTU9ZHZQYlIpHLGivNJqdYtljzkc
            JE0LCTo5rp2r6+lLr/psv37USEf9t8bpK6xUEnD/FUdha8syx7+FFAnxMx82ltmF
            tse+mXYQToguuw4VSGLFNp1MLQTVgDxU4m2KJoAf5IqugpRGoKU7WwxYFBUo1rNL
            2wL7mUWlCkndDoScYPymvVrisAgpBtOJA3AZm4NgKcCJ8IQRhAW1uacSdbMWK+CR
            KMxw2RWJow4pVh9hvBVUbizZxCxccVQJFUeoQ1FpjW4n3pbUwT2d0xTzbCNH+9DS
            XgGwmJz315vaR/37Q8HUQNBbj9InxvAxiCWv9xiRJsUrKMN+FW7hPhKlnFp1lTHg
            YXuTvawm8f72/Wc15PfqtWr32PYIDgf0OfyStARJd70U9C77W5DCMuwRjJu0R2A=
            =XsuR
            -----END PGP MESSAGE-----
          fp: 4ED64FA5BBF73612035B86B20C414B6F2BA7BB19
        - created_at: "2026-09-05T10:09:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DKzNQps96PfoSAQdAiEsHBS7G2M2OG3ANPsdFGodvgwasya7IMI4IFovqazQw
            hEsczC0VbwO+y0yUmz5kNZn47pMvim7SgBdjo03fMNSckGEl7zxX5m9w6Bnqc0/a
            0l4BWM+6Hsnl6MCdGuHQWTQ6gVUc6/ycfUqIMqfsEwvF3qAxCOZq62J99xoxouGa
            yi6rNFj2w+FHyH0/4uKxE9bVjivM8FP6T4tIvCbaBAIrRbYQ3KPp85XC2zXkFT90
            =kXAN
            -----END PGP MESSAGE-----
          fp: 2CA3E8ADF4A11935CC7554069BA899CFBEE59D40
    unencrypted_suffix: _unencrypted
    version: 3.11.0
