wifi_ssid: ENC[AES256_GCM,data:L7+4Y9b1R5p2,iv:mlmna8D9kW3FNCQJTb2M4Mh3GzzxBiO0fGc9j45APGk=,tag:cR5dcagsZS1fFWESmVgdlQ==,type:str]
web_password: ENC[AES256_GCM,data:4CkeUWY=,iv:u0NE2Zgru3PznuCEbnEWj6AHK5dK1YCas+6mNdIY7g0=,tag:vL6n04LTIz3aClcWt7uvDQ==,type:str]
ota_key: ENC[AES256_GCM,data:6KlYFq3nIEkz7Imm64o5mHEr9anpf7YiYToJNpenHTQ=,iv:CQ9WeReDlHMWFWDJyKLzaS+jP4iMoCutB5Dk93Jo0xQ=,tag:S0WhhuPfh62mDUnEEtSU5Q==,type:str]
api_key: ENC[AES256_GCM,data:96Cg/hhr/miIwlPNy/4IAMfWVqZcjEhXb+Klru/IEK4R9suQrhI5uvJWPs0=,iv:R7+a+5FQMyLH0+tAp5q7SUFoa3o2ydiQXKDYK0gwMac=,tag:O3X9gbLwnd8mcL5knzJtiA==,type:str]
sops:
    age:
        - recipient: age1evpz8q2vsh029ph5v63muxk7ml7vg99ygqd7vg09e2azuff2a3pq34lal4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZmhPaGNBRGZmMFdGVnFN
            WnVtUEVscHRTQ2xkNC9tdVREdDRyTEFHV1J3CkN1YlZRUXZ0OUthWkhZY2NNVlJJ
            ZzNyVE9pOThHU3hQSFhwajZDYXFwTmMKLS0tIEUvZFY0dU52OWpIdWRiR0tzMlhi
            d2NqTGsxSVRRdDRYV1BVUGxZdkdJZHcKsxCyqRZFF3obpXZAS0iYwbUOMuYJcqR4
            wVzsuRAmw/j0ufROLnUUZ7sM9wbkN4dnMlvdOaLutaxkrDM2lufDVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T11:57:51Z"
    mac: ENC[AES256_GCM,data:pSRlvtQdWnN4rgygVLebZiykDyx75gp0dURUHsCz1IghF2a58T3DwulPFINHUmDtZaXVXU3iEGfyt8YEZHzK3ORgIBzbV2yq7vQLSv1Kp8CQMeIyJJAVEwBdseHdfn6BIQ7h2Hi8IXFepKDH3FC7QIx10LJADEUsIlbj25cpYOM=,iv:AC/yVkIqaVR26/qlUfAbjTtuoKZ7Bm4prY4UcoYvUqg=,tag:U+Q0JS3ck6+pE73E7dAs4g==,type:str]
    pgp:
        - created_at: "2026-04-19T00:34:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+IYLURd8XmyAQ//V436bz+rugvxMHjEd33WhxYLGt4ePJCFGe2EEcOJj8UA
            7PI8WuN49SwTEQephT7diJx52tnG9dUyXXa4KpMkfexS0ovkCI6/TTTVO62HCv90
            uI7lgOwjgm4KCyh7YdDDdq4dA/uW/5LymZ95byv8EaYxdGlouuCcY6LlK3m52Ewt
            VxGsQobivwtBwLemFjsKWwqQTbM1Gz0IPJmV5Da0lEQYMdGgjNnsL1Dq2A5MIr/q
            s/yXD4MMXM59l+IduWglPQ5A7U+q+WO8Rb4CJDFs7iJB9wpgj1wtLHM16Rm22BYS
            1RdLrK7NchVv+3ApLWVtdcjOHNL47XMHDiuIyoy6/hsDH2B9JK6QP8tbn8+GCE0F
            sZiX+DkvDbEdw5KB2o8c64KHI7+lfaxasmtc0p+XRRpUajVJmYc1FlUqu/fUSCf5
            SDiBj1jM9ur7m+rYqO+Q9moaE1VmDofpBKxxQO4gXlFMvloVUAojhwNf24xhHao/
            V1JsLKMYz47Yj8lVb6wZENO6sIfd0lIQyAHFGwRYOXjKB3SjfjbJNhPGG9QQmHmr
            LKNHSY0JH5/4ZVa2v6XFxdsV0b0KXPCP3ybtR7pIQg6GshzHcFSAuNSiKEtLg5pB
            RExX/0XXbcd966pQyDVbWnD5HIeFvvNqePcqfaC2Ex156pZ0FzfxK9l9Zqbet0HS
            XgFPnybtAM5+KTtk5U/8WCLxRPastK9hsUL2KXTsDlgUWWVMJTtICd2bkFvoicHm
            mTGzmcXUpdopYwbMc4Q/eBkuEQdjSoHpiQXCES3t3GBsEDkoOvq+c7J9T7C6ksA=
            =bJ01
            -----END PGP MESSAGE-----
          fp: 4ED64FA5BBF73612035B86B20C414B6F2BA7BB19
    unencrypted_suffix: _unencrypted
    version: 3.11.0
