mosquitto-password: ENC[AES256_GCM,data:zzM47rbv2GiZpbellzlditxVDOjw+l/tyw==,iv:JpFldlSYNlhIMvoCAxXNh17ht7zcE2QYRa0osrEcOX0=,tag:UYyuYPKaU9taW1w0lLcBug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQUhTbW9DU2VEWDhtcTdl
            NHYwazhPVXI1OVlJbHc3NFIzTXlqN3FmNGxvCnJoY1BSanV0dlZKNVBQSFQyQUd3
            QzVwVU1pUG9mZUlKc29IMkN5NUtOdk0KLS0tIGNsZzZTTFI0S3c1WFd3OG5TZGRn
            a2czL3F5RGxXOW1wc01LWWk1blRpdEUK+Os58FJm4BN02xgVGd3wWHi/Gf6624XH
            gySBB8LlvGlOQ4ELM2mi8g+15eFn9NORFHrsxVB4obLjbibOPi/82A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1evpz8q2vsh029ph5v63muxk7ml7vg99ygqd7vg09e2azuff2a3pq34lal4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsanRYR1pDUnBTNlJoR3Rq
            Tkg4aHA5S1dZcFQ4REJhOWdUZ2tORTdXZTBzCnRoTmFtamFLa2hGL1NBc1VXMHlC
            MldlSDlHQ3NramxEbzJBeTNjMi83NnMKLS0tIDBJR1VyT0NDZXFwd1ZwV21sS2VU
            M1VPek1haUFaRUJPYVVnZk1vaWJjeGcKtRboHe8TZVk9qcJMUCp5JS0QQxV250G/
            kLG2nzIH4dZx0W1lo76943/zI3Tca/rm1mlZvYQ7liVRbLPNXyIcKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykqrhesjvasdz8hr2yguveevh5prdt2hxfchsa8d29np9zc5udfqmt8gln
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBha2hVUDhaR2laS29ERlkv
            YXBZOFA3MitGZTNGUEUxL3RGa1lmVHFDMkRNCmc4VEt4ZkJ5Q242NWR1MnJ2Rmsv
            czhJZEI0alQ0TDhXSTcvTTZOMDYzSzQKLS0tIHBqV2N4MkhNS2VFTGtpWUUvQzF2
            dHpjdjh0ZHNkMlRITVdrc01VSk9iaFUK+ExgRNCLeV/xvBOAuB4MuzN+OXscqbwm
            i40/C8MUFDcaoZBOZrsbutap5OgzL5b5OsTquq4CEZTBdFD5lcWKbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzzz6c85g7p2r57k0hkejs6097k8thqajt42pmj5xnp8l2h0v9qs7f5qsy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNzZRTTkrRVNjMnBpMVZT
            dyt1NFJ0MDg5YSs5Y2w5czVENUpqeFJMNzBVCkZLRGVkRVgvT0R6NkhkRFBxNUo4
            ZXRPa3JCa2ZXNE9lcWhKSlljTThYVGcKLS0tIDdkN2pIU0dRQUtsR1lzSk1EaHB1
            UEJ1MEN0cVpCelh5NXd1UFJlWVBaM1EKL/tYg0kYRyETo9Qy651ID6Ul/Fr9v8oq
            sgBMGSi3twLl4G638MuVNrcgP0CY7RSn8gb2Jm5niLbJH5sVoQj5JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gnp3jhva7gv0dqdame33fvpeam9lt47rj3nqgujgynh3m7k6lyxqvdmzq0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb3lWL21Cb3Y0ck9rMS9v
            Y0RuN3VuMTMyK2JGQ21JZ0RLVkFpcWk4b0NvCndyVkhnSmhLVmIvN0ZsUTM3ZGhG
            R05RcnJMZytvV2UzQVp5Mm5DQUlBQUkKLS0tIGljaFVOY1hCczZNRzBRMVdNckY0
            UDZMcVhiNHk4OTdyK016SEhJWml1WTAKVO5G6yvd34dD4JWkuwrIZxFnZXV81mQv
            PA7LAiSuN0ilhfiDvlQQcDIHoJiHvlgg4bxfElzJah7WMH7VjXH0Pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jjkq5kttpy9dhvn64s9ht7e0vndqx6glx43uc3xsd9q0ard5ffqta0jvn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWUVXcTZHNWU5S1FTOHVI
            MW1YZ1FqVmpVMHNWc0w5elh6NldUZ1hIemw4Cm5BWXkvY3hzN3NtSkR2Y1NjbDho
            RktiSHRFLzJ1cExmTDB1SFZGc0k3ZzQKLS0tIGhjc2x1RklMS1o3N3I3RXhpYWNT
            S1hsWHlQZE0zT2hNQVVWeDIyOTIzam8KbRlggOtkTuLf7quMTw8V3t2Cx1QEg+Tn
            XMTZ8+kFuszhPj9ENWr7CoR6lbycejCZM6AiOHaLfrPfBEG9h8MyUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1edvqxtg7a28w3sjvl2g59cz9sh2l9n5zsl8ad0x20cdqvqnyg9aqc970x6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQUY3UU9IOWx4ZUFwQk9O
            RW1FazJRRlZZMGVtazE1VDdacmxRL2RwcFFnCnA2N2NmWmErWVY4NlRyRXM2ejBZ
            SlN1U1llbWUvcjRrdjlWUWFtQk1yTDgKLS0tIHVxOUEvd3hEV0tHYkVBczdxWHRT
            ajg1TUdrRjVwb2RxWndZYVdoVkFFU1EKmfflLQIjNRTNwlcDrK0Nke8/CjkzYnIR
            wzTaoUW1yJutTGE6mVt9CUXrzwAxbM+Eeergmn6vlUein2RDAb/RqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xn4v4pxxvs2mtphvd0wy95qde0q7cuvj4nht8gt7y7wnmhd2nusss7h9en
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRnVEQVJGWlp0RHZVMzRn
            Yk5hZ0dtVG5PZFV1WDRrOFZRWjRUY2pPQkFvCjMrWmkzTHE4U1cwRThnZVZiNCtv
            bVdpMS9mb2U5OHlUYUx2TjEvWEFTYncKLS0tIGkxYjNBNm9IZXdMSzFKZ1FHU2Vs
            VHlVZktjM1NMUHp1Z0p3WXZIZW93YTgKVOea0BQ3WnfHnk3A6+VJH1G2qim6hBaU
            bAfdsSA0H3b4zC3eedFUmf12tfr7knm2umDuwZ0oqTE6vhMMWO0p5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10zjqq6aevnwg9xkmpeq40u9utx8k09gw5r4qkrkvrc9hmjdv8szqre99zq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWlRWWmpjT2JIbXkxMkJT
            OUJkM3pQYU5KdmdMVFM1ZllPcDFCMjlna0NrCk45dkV2ckQ4aGJ4NCt6Z2tVTU5u
            b2V5MTNUcXFCTy9kV2NxeXVRbS9MYTgKLS0tIEltdXIwVWhEMnJiTERER2hjdHJN
            b1M0UTVuRVkxaXZhR3d6Y2Nvdm1XakUKHvXdqq9QCqblpTM0M98OnRxdotxsIcRH
            WtiNHvt32H2L94rqu/V8VPcPfZVLY2ud86BctrgDZCtt2tYsv1RApA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tmy38cwuf2jsjj72s6w55jsvgyf9207mxw29at58u4x9m68mg34qk67yrt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNFhPdkFtQ0h6WEpJbkUy
            dyt3UmVGaG9TcEFsbDllci9KcFJCUDVGcWgwCkJvT0pGY0FGUmFPdURBeEczTi9q
            Zms1Y3o0ekx4RUVlYno5M0JOVDFEUWMKLS0tIDlNdnhkVFV3M0ZiaXN3UG45Q0JS
            REh1RWdFeVJnenFGY0haeldMYWxZeUEKbiZDqyC+bQpA+FWY2T5iZffl3WWBRnsB
            I6/z40lt6N9c2qL/jcKrNTFmD6UIhz+aZXCyfAPa7MOOMR0BKBwlwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l397cc000vd660wynywsvd30adr4hwa3s4se5c83gglfmm7s23asgjuaw5
    lastmodified: "2026-02-23T14:16:40Z"
    mac: ENC[AES256_GCM,data:mt9DN/3yTmlp887A4Lo4ev+slqFwBYfV2/+s/xDheBayfCjelXv2C2o1TuzwDJN8N3OuNOxLePPabFkUxr9N9fUXDNpJ/e11iBPKRqvt90df39O5T/R9l9F2Vmluz3WMW+ay6LfU3ebN1B4EuoRlhgy/pk0aFwkecuG0f7CU5Es=,iv:vMiBTirInxarRPl0DlRwHRSQ8DGciD2gY7PjZNh2zJo=,tag:JbeGvMO0MI+vta3rl4m6HQ==,type:str]
    pgp:
        - created_at: "2026-07-31T08:31:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+IYLURd8XmyARAAovzZ2VYCD2UiH34vu4XfcNUz+h5FH+bEF56PuGLmfF5V
            xSRBHhaBBUZva6FuMmzC58rzHJz60E5gyMqC2IYRBMFGZxB5QR9oBfeqct4qQ2v1
            +j2Oil8EwQstQWmAh0/1tK+Yz2tpoE09/jqmPDf8kUve+2gi5jfl8JApcgLGV6bv
            7XeQJYorOD6KWPRPxXZCwW1kN4rXjm8stAX/vywVAGC8392I818gTmJwaCX9XMTA
            /AHF9Zr9RWbWsrMtmyYYDTA6anSuaMqxp6SXczY6nRmHUdEnJHS0ROE7dSa2oRiq
            II9nkxcUGCwUVZF1IVl/BY8JNeYTDnDrZ+iuZQSbcemGJDT2yys01BWHqP6YXA0U
            diezo74r6lCTWFdKNc+NADchScrnnrlumFIlwIQSnJXkp6ghRFj34e0/KsU7gP8p
            y+ab4ILBvVmELZQ2Byhc13Zs7T9r2DsWF8g9CiYOEy6+4eI1OlcuvJrU2CwP77N5
            3HC5PtU1ylSYvwVsaZrkrsC3bBppRzl5WshfsmCxG5g11fMftqvLVuOYprD0zTtv
            X/9jcy56K6g9sxcc3OWeUah6IAFoztwsCdLs++FQ9bAS9u07i/M9QZQyOHWkOxAz
            aKILm0kCsV3frEU0IHmAg7izFsrbkTFcS+xzTRTISKgxnvLZP3+sI08i4OAN+fzS
            XgGvUj0UJFTJlsY1ajJi1srD7FfPBeI3y8BOqbyY9S9Z+pR8uCwh+GU8YxDkiEgf
            ovCgcdIlbgyQpzYeI9rPJvF718MxN4iHC5qxeEltLRNSqdrSfU1vHZa4TQyOJTI=
            =lahX
            -----END PGP MESSAGE-----
          fp: 4ED64FA5BBF73612035B86B20C414B6F2BA7BB19
    unencrypted_suffix: _unencrypted
    version: 3.11.0
